remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "Eval4RAG: Workshop on Evaluation of RAG Systems"
description: "April 10, 2025 -- Co-located at ECIR 2025"
google_analytics: G-M627Q96840
